#services:
#  - docker

language: go

go:
  - 1.11.x

go_import_path: github.com/ncabatoff/json2prom

script:
  - go build

after_success:
# - docker login -u $DOCKER_USER -p "$DOCKER_PASSWORD"
  - test -n "$TRAVIS_TAG" && curl -sL http://git.io/goreleaser | bash